### ISSUE TITLE
There's no precache lines

### ISSUE THREAD

**Issue by danylopez123** [wootguy/ClassicModeDeluxe#4]
Without the precache lines, it won't make this for the FastDL.
Do you think you can fix that by adding the precache lines or is there another way for it?

**Comment by wootguy** [comment]
The precache lines are here:
https://github.com/wootguy/ClassicModeDeluxe/blob/726f6f154c8bd4f9ee1958d8c866778aa7b13bbc/scripts/maps/ClassicModeDeluxe/ReplacementLists.as#L456-L526
Is there a specific model/sound that isn't working?

**Comment by danylopez123** [comment]
I dont know.. must be everything that isn't precached.
I checked the HFS program which is what i use to share my files to make it as FastDL and i was checking that there wasn't any of the ClassicModeDeluxe content being downloaded to someone.
And yes, i did port fowarded.

**Comment by wootguy** [comment]
I guess this is a fastdl problem then. The server would crash if the models were used without being precached, and the sounds wouldn't be sent at all. I don't what causes FastDL to break though.

**Comment by danylopez123** [comment]
That is weird...
All of my other files that's not from the ClassicModeDeluxe like maps and their stuff, custom playermodels and custom stuff from other plugins works fine for the FastDL, i dont understand why not with this.
Well.. i tried.
